version: '3.1'

services:
  gosbot:
    container_name: gosbot
    hostname: gos.domain.tld
    image: gosbot:latest
    restart: always
    environment:
      - TZ="Europe/Berlin"
      - GOSBOT_KEY=abcdef12345678980
      - GOSBOT_PORT=10513
      - GOSBOT_UPDATE=1
    volumes:
      - ./gos:/opt/gosbot
