version: '3.1'

services:
  gosebot:
    container_name: gosebot
    hostname: gose.tsbots.de
    image: gosbot:latest
    restart: always
    environment:
      - TZ="Europe/Berlin"
      - GOSBOT_KEY="XXX"
      - GOSBOT_PORT="513"
      - GOSBOT_UPDATE="true"
    volumes:
      - ./gos:/opt/gosbot
    ports:
      - 513:513
